SELECT 
DATA_POT_PERFORMANCE_PWS_SPOTS.EVENT_ID,
DATA_POT_PERFORMANCE_PWS_SPOTS.YEAR,
DATA_POT_PERFORMANCE_PWS_SPOTS.SITE_ID,
DATA_POT_PERFORMANCE_PWS_SPOTS.STATION,
DATA_POT_PERFORMANCE_PWS_SPOTS.POT_ID,
DATA_POT_PERFORMANCE_PWS_SPOTS.FK_GEAR_PERFORMANCE_CODE,
DATA_POT_PERFORMANCE_PWS_SPOTS.SAMPLE_POT

FROM DATA_POT_PERFORMANCE_PWS_SPOTS
WHERE 
(((DATA_POT_PERFORMANCE_PWS_SPOTS.STATION) Not In ("E","E1","E2"))
	AND DATA_POT_PERFORMANCE_PWS_SPOTS.FK_GEAR_PERFORMANCE_CODE = "01");


