SELECT 
CPP_1.YEAR,
CPP_1.EVENT_ID,
CPP_1.SITE_ID,
CPP_1.STATION,
CPP_1.POT_ID,
CPP_1.SAMPLE_POT,
NZ(CPP_2.all_Cnt,0) as all_Cnt,
NZ(CPP_2.all_Kg,0) as all_Kg

FROM CPP_1

LEFT JOIN
CPP_2 ON (CPP_1.POT_ID = CPP_2.POT_ID)
 AND (CPP_1.EVENT_ID = CPP_2.EVENT_ID)

WHERE (((CPP_1.FK_GEAR_PERFORMANCE_CODE)="01"));